from typing import Protocol
from uuid import UUID

from ..domain import Item


class IItemRepo(Protocol):
    async def add(self, item: Item) -> None: ...
    async def get(self, item_id: UUID) -> Item | None: ...
    async def list(self, limit: int, offset: int) -> tuple[list[Item], int]: ...
    async def update(self, item: Item) -> None: ...
    async def delete(self, item_id: UUID) -> bool: ...
