from typing import Protocol, runtime_checkable


@runtime_checkable
class IMetricsSink(Protocol):
    def increment(self, name: str, value: float = 1.0, **labels: str) -> None: ...
    def set_gauge(self, name: str, value: float, **labels: str) -> None: ...
    def observe(self, name: str, value: float, **labels: str) -> None: ...
